### ISSUE TITLE
Help Error While running Make

### ISSUE THREAD

**Issue by Bhood23** [raspiduino/sm-n950f-kvm#1]
root1@DESKTOP-GRME42H:~/sm-n950f-kvm$ arch=arm64 CROSS_COMPILE=./toolchain/gcc-cfp/gcc-cfp-jopp-only/aarch64-linux-android-4.9/bin/aarch64-linux-android- make -j8
INFO: CC is ./toolchain/gcc-cfp/gcc-cfp-jopp-only/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     scripts/mod/devicetable-offsets.h
  CHK     include/generated/utsrelease.h
  CHK     include/generated/timeconst.h
  CHK     include/generated/bounds.h
  CHK     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
make[1]: 'include/generated/vdso-offsets.h' is up to date.
  CHK     include/generated/compile.h
security/defex_lsm/Makefile:57: [DEFEX] VTS false
security/defex_lsm/Makefile:79: '[DEFEX] file_list found'
make[1]: *** No rule to make target 'firmware/exynos8895_acpm_dvfs.fw', needed by 'firmware/exynos8895_acpm_dvfs.fw.gen.o'.  Stop.
make: *** [Makefile:1037: firmware] Error 2
make: *** Waiting for unfinished jobs....
  CC      drivers/bluetooth/bcm43xx.o
  CHK     kernel/config_data.h
In file included from include/linux/linkage.h:6:0,
                 from include/linux/kernel.h:6,
                 from include/linux/delay.h:10,
                 from drivers/bluetooth/bcm43xx.c:23:
drivers/bluetooth/bcm43xx.c:80:15: error: 'check_bt_op' undeclared here (not in a function)
 EXPORT_SYMBOL(check_bt_op);
               ^
include/linux/export.h:57:16: note: in definition of macro '__EXPORT_SYMBOL'
  extern typeof(sym) sym;     \
                ^
drivers/bluetooth/bcm43xx.c:80:1: note: in expansion of macro 'EXPORT_SYMBOL'
 EXPORT_SYMBOL(check_bt_op);
 ^
make[2]: *** [scripts/Makefile.build:267: drivers/bluetooth/bcm43xx.o] Error 1
make[1]: *** [scripts/Makefile.build:411: drivers/bluetooth] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:1037: drivers] Error 2
  CC      sound/soc/samsung/abox/abox_adaptation.o
In file included from include/linux/linkage.h:6:0,
                 from include/linux/kernel.h:6,
                 from include/asm-generic/bug.h:13,
                 from ./arch/arm64/include/asm/bug.h:62,
                 from include/linux/bug.h:4,
                 from include/linux/io.h:23,
                 from sound/soc/samsung/abox/abox_adaptation.c:12:
sound/soc/samsung/abox/abox_adaptation.c:75:19: error: 'maxdsm_dsm_read' undeclared here (not in a function)
 EXPORT_SYMBOL_GPL(maxdsm_dsm_read);
                   ^
include/linux/export.h:57:16: note: in definition of macro '__EXPORT_SYMBOL'
  extern typeof(sym) sym;     \
                ^
sound/soc/samsung/abox/abox_adaptation.c:75:1: note: in expansion of macro 'EXPORT_SYMBOL_GPL'
 EXPORT_SYMBOL_GPL(maxdsm_dsm_read);
 ^
sound/soc/samsung/abox/abox_adaptation.c:111:19: error: 'maxdsm_dsm_write' undeclared here (not in a function)
 EXPORT_SYMBOL_GPL(maxdsm_dsm_write);
                   ^
include/linux/export.h:57:16: note: in definition of macro '__EXPORT_SYMBOL'
  extern typeof(sym) sym;     \
                ^
sound/soc/samsung/abox/abox_adaptation.c:111:1: note: in expansion of macro 'EXPORT_SYMBOL_GPL'
 EXPORT_SYMBOL_GPL(maxdsm_dsm_write);
 ^
make[4]: *** [scripts/Makefile.build:267: sound/soc/samsung/abox/abox_adaptation.o] Error 1
make[3]: *** [scripts/Makefile.build:411: sound/soc/samsung/abox] Error 2
make[2]: *** [scripts/Makefile.build:411: sound/soc/samsung] Error 2
make[1]: *** [scripts/Makefile.build:411: sound/soc] Error 2
make: *** [Makefile:1037: sound] Error 2

Could you fix this error?

**Comment by Bhood23** [comment]
FIXED by deleting export command

**Comment by raspiduino** [comment]
Please note that this is the original kernel source, and the source with
KVM is still in process. Please wait, thanks!
